service: notes
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}


plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "notes"
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: true

functions:

  addNote:
    handler: index.add_note
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: post
          cors: 
            origin: '*'
            headers: '*'

  getNotes:
    handler: index.get_notes
    logRetentionInDays: 30
    events:
      - http:
          path: /
          method: get
          cors: 
            origin: '*'
            headers: '*'

  getNoteById:
    handler: index.get_note_by_id
    logRetentionInDays: 30
    events:
      - http:
          path: /{note_id}
          method: get
          request:
            parameters:
              paths:
                note_id: true
          cors: 
            origin: '*'
            headers: '*'

  updateNote:
    handler: index.update_note
    logRetentionInDays: 30
    events:
      - http:
          path: /{note_id}
          method: post
          request:
            parameters:
              paths:
                note_id: true
          cors: 
            origin: '*'
            headers: '*'

  deleteNote:
    handler: index.delete_note
    logRetentionInDays: 30
    events:
      - http:
          path: /{note_id}
          method: delete
          request:
            parameters:
              paths:
                note_id: true
          cors: 
            origin: '*'
            headers: '*'

